import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    default: "NextJS Learning",
    template: "%s | CZ",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: "lightblue", padding: "1rem" }}>
          Header
        </header>

        {children}
        
        <footer style={{ backgroundColor: "lightblue", padding: "1rem" }}>
          Footer
        </footer>
      </body>
    </html>
  );
}
